### PR TITLE
fix(homepage): use subPath for each config file

### PR DESCRIPTION
**Pull request by gfaugere**
Fixes https://github.com/benphelps/homepage/issues/2040

### CODE REVIEW

**Comment by gfaugere** [comment]
Tested it against my own deployment, looks good to me but this is my first time working with an helm chart which depends on an other chart, so this might not be correct - let me know! :)

**Comment by shamoon** [comment]
@jameswynn think you'll have a minute to look at this? Thanks 🙏

**Review by jameswynn — APPROVED** [review]

**Comment by jameswynn** [comment]
@gfaugere Please bump the chart version to 1.2.3

**Comment by shamoon** [comment]
Sorry for the off-topic, can anyone here explain how this fix would translate to the suggested manifests at https://gethomepage.dev/v0.7.3/installation/k8s/ ?

In particular https://github.com/gethomepage/homepage/issues/2172 but it looks to me like the custom.css files are handled the same as the homepage yaml files https://gethomepage.dev/v0.7.3/installation/k8s/#__codelineno-4-16 vs https://gethomepage.dev/v0.7.3/installation/k8s/#__codelineno-4-11

**Comment by jameswynn** [comment]
I think that block should be changed to something like:

```yaml
        volumeMounts:
        - mountPath: /app/config/custom.js
          name: homepage-config
          subPath: custom.js
        - mountPath: /app/config/custom.css
          name: homepage-config
          subPath: custom.css
        - mountPath: /app/config/bookmarks.yaml
          name: homepage-config
          subPath: bookmarks.yaml
        - mountPath: /app/config/docker.yaml
          name: homepage-config
          subPath: docker.yaml
        - mountPath: /app/config/kubernetes.yaml
          name: homepage-config
          subPath: kubernetes.yaml
        - mountPath: /app/config/services.yaml
          name: homepage-config
          subPath: services.yaml
        - mountPath: /app/config/settings.yaml
          name: homepage-config
          subPath: settings.yaml
        - mountPath: /app/config/widgets.yaml
          name: homepage-config
          subPath: widgets.yaml
        - mountPath: /app/config/logs
          name: logs
```

**Pull request merged**
